name: TownyWeb
version: '${project.version}'
main: net.worldmc.townyweb.TownyWeb
api-version: '1.21'
authors: [Ezekiel Pari]
folia-supported: true
libraries:
  - "io.javalin:javalin:6.1.3"
  - "com.fasterxml.jackson.core:jackson-databind:2.13.2"
depend: [Towny]