name: TownyWebBridge
version: '${project.version}'
main: net.worldmc.townywebbridge.TownyWebBridge
api-version: '1.20'
authors: [Ezekiel Pari]
folia-supported: true
libraries:
  - "io.javalin:javalin:6.1.3"
  - "io.javalin.community.ssl:ssl-plugin:6.1.3"
  - "org.slf4j:slf4j-simple:2.0.11"
  - "com.fasterxml.jackson.core:jackson-databind:2.13.2"
depend: [Towny]